### PR TITLE
Brought the template up to supporting Visual Studio 2017.

### PR DESCRIPTION
**Pull request by slax0r**

### CODE REVIEW

**Comment by RobThree** [comment]
I can't check it currently, but if you ask me you only need to change the `InstallationTarget ` in [DebuggableOwinServiceSetup/source.extension.vsixmanifest](https://github.com/RobThree/DebuggableSelfInstallingOwinService/blob/master/DebuggableOwinServiceSetup/source.extension.vsixmanifest). I don't see why the other changes would be required, nor do I see why you'd change the `InstallationTarget` from `[12.0,15.0)` to `[15.0,16.0)` instead of `[12.0,16.0)`? Why would we drop support for older VS versions?

**Comment by slax0r** [comment]
Dude,  I needed this package for a project and you hadn't updated them yet. So I did it myself to suite my needs. If you want to reject it, its no skin off my nose.  So I only have VS2017 and it absolutely requires now that the vsixmanifest has a prerequisites block.  Other than that I didn't try different configurations for the InstallationTarget.  But you are correct those are the only two things that needed changing.  Afterword it worked like a charm for me.  If/When I get some more time, Ill submit a more proper pull request for both projects.

**Comment by slax0r** [comment]
Incidentally, Im not super experienced at creating or maintaining VSIX packages.

**Review by GioviQ — APPROVED** [review]

**Comment by RobThree** [comment]
See 8870a3d0a327cc184183e10cd5470f03d203bbd2 and [v1.1](https://marketplace.visualstudio.com/items?itemName=RobThree.DebuggableOwinService)

**Pull request closed without merging**
